=== NataliaPalej/web-dev2-labs/.Semester2/Lab2_Schemas/Personal/personal.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchem"
            targetNamespace="http://www.personal.com"
            xmlns="http://www.personal.com"
            elementFormDefault="qualified">
    
    <!-- schema document -->
    <xsd:element name="details">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="age" type="positiveInteger"/>
                <xsd:element name="dob" type="xsd:date"/>
                <xsd:element name="year" type="xsd:gYear"/>
                <xsd:element name="month" type="xsd:gMonth"/>
                <xsd:element name="day" type="xsd:gMonthDay"/>
                <xsd:element name="time" type="xsd:time"/>                
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== NataliaPalej/web-dev2-labs/.Semester2/Lab2_Schemas/Personal/PersonalDetails.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<details xmlns ="http://www.personal.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.personal.com personal.xsd">
    
    <name>Joe Bloggs</name>
    <age>10</age>
    <dob>2000-01-22</dob>
    <year>2000</year>
    <month>--01--</month> <!-- http://www.java2s.com/Tutorial/XML/0060__XML-Schema/ThegMonthdatatyperepresentsaGregorianmonththatrecurseveryyear.htm -->
    <day>---22</day> <!-- http://www.java2s.com/Tutorial/XML/0060__XML-Schema/ThegDaydatatyperepresentsadayofthemonththatrecurs.htm -->
    <time>10:12:03</time>
    
</details>
