=== NataliaPalej/web-dev2-labs/.Semester2/Lab1_XML/house.dtd
<!ELEMENT house (address, size, bedrooms+, toilets, ensuite, price)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT bedrooms (#PCDATA)>
<!ELEMENT toilets (#PCDATA)>
<!ELEMENT ensuite (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== NataliaPalej/web-dev2-labs/.Semester2/Lab1_XML/house.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE house SYSTEM "house.dtd">

<house>
    <address>Athlone</address>
    <size>120m2</size>
    <bedrooms>Master Bedroom</bedrooms>
    <bedrooms>Double Bedroom</bedrooms>
    <bedrooms>Box Room</bedrooms>
    <toilets>2</toilets>
    <ensuite>2</ensuite>
    <price>600.000</price>
</house>
