<?xml version="1.0" standalone="yes"?>
<!DOCTYPE note[
<!ELEMENT note (to, from, heading, body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
]>

<note>
    <to>Andy</to>
    <from>John</from>
    <heading>Fishing</heading>
    <body>Lough Mask this weekend</body>
</note>
