=== NataliaPalej/web-dev2-labs/.Semester2/Lab2_Practise/regEx/regexp.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.regexp.org"
            xmlns="http://www.regexp.org"
            elementFormDefault="qualified">
    
    <!-- New DataTypes Declaration -->
    <xsd:simpleType name="costType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\p{Sc}\p{Nd}+(\.(\p{Nd}){2})"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="quantityType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="((\p{Nd})?){2}\p{Nd}"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="titleType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="Mr.|Ms.|Dr."/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="fnameType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\p{Lu}(\p{Ll})+"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="addressType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\p{Lu}(\p{Ll})+\,\sCo.\s\p{Lu}(\p{Ll})+"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="creditCardType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="VISA|Access|Mastercard"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="numberType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(\p{Nd}){16}"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="expiryType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(\p{Nd}){2}\/(\p{Nd}){2}"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="cvvType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(\p{Nd}){3}"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    
    <xsd:element name="details">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="item">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="cost" type="costType"/>
                            <xsd:element name="quantity" type="quantityType"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="from">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="title" type="titleType"/>
                            <xsd:element name="fname" type="fnameType"/>
                            <xsd:element name="surname" type="fnameType"/>
                            <xsd:element name="address" type="addressType"/>
                            <xsd:element name="payment">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="creditcard" type="creditCardType"/>
                                        <xsd:element name="number" type="numberType"/>
                                        <xsd:element name="expiry" type="expiryType"/>
                                        <xsd:element name="cvv" type="cvvType"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== NataliaPalej/web-dev2-labs/.Semester2/Lab2_Schemas/RegExp/regexp.xml
<?xml version="1.0" ?>
<details xmlns ="http://www.regexp.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.regexp.org regexp.xsd">
    
    <item>
        <cost>$123.45</cost>
        <quantity>19</quantity>
    </item>
    <from>
        <title>Mr.</title>
        <fname>Joe</fname>
        <surname>Bloggs</surname>
        <address>Athlone, Co. Westmeath</address>
        <payment>
            <creditcard>VISA</creditcard>
            <number>1234123476547643</number>
            <expiry>12/05</expiry>
            <cvv>123</cvv>
        </payment>
    </from>
</details>
