=== NataliaPalej/web-dev2-labs/.Semester2/Lab2_Schemas/ChampionsLeague/CLTeams.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.CLTeams.org"
           xmlns="http://www.CLTeams.org"
           elementFormDefault="qualified">
    
    <!-- Declaring new dataType -->      
    <xsd:simpleType name="groundType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Anfield"/>
            <xsd:enumeration value="The Emirates"/>
            <xsd:enumeration value="Stamford Bridge"/>
            <xsd:enumeration value="Etihad"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="numChampsType">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="0"/>
            <xsd:maxInclusive value="5"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:element name="CLTeams">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="year"/>
                <xsd:element name="team" maxOccurs="4">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="owner" type="xsd:string"/>
                            <xsd:element name="ground" type="groundType"/>
                            <xsd:element name="numChamps" type="numChampsType"/>
                            <xsd:element name="challengers" type="xsd:boolean" default="false"/>
                        </xsd:sequence>
                        
                        <!-- declaring team name attribute -->
                        <xsd:attribute name="name">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:enumeration value="Man City"/>
                                    <xsd:enumeration value="Arsenal"/>
                                    <xsd:enumeration value="Liverpool"/>
                                    <xsd:enumeration value="Chelsea"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:attribute>
                        <!-- end of team name attribute declaration -->
                        
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence> 
        </xsd:complexType>  
    </xsd:element>

</xsd:schema>

=== NataliaPalej/web-dev2-labs/.Semester2/Lab2_Schemas/ChampionsLeague/CLTeams.xml
<?xml version="1.0"?>
<CLTeams xmlns ="http://www.CLTeams.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.CLTeams.org CLTeams.xsd">
    
    <year>2015</year>
    <team name="Man City">
        <owner>Sheik Mansour</owner>
        <ground>Etihad</ground>
        <numChamps>0</numChamps>
        <challengers>true</challengers>
    </team>
    
    <team name="Arsenal">
        <owner>Unknown</owner>
        <ground>The Emirates</ground>
        <numChamps>0</numChamps>
        <challengers />
    </team>
    
    <team name="Chelsea">
        <owner>Abramovich</owner>
        <ground>Stamford Bridge</ground>
        <numChamps>1</numChamps>
        <challengers>false</challengers>
    </team>
    
    <team name="Liverpool">
        <owner>FSG</owner>
        <ground>Anfield</ground>
        <numChamps>5</numChamps>
        <challengers>false</challengers>
    </team>
    
</CLTeams>
